AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-s3-bucket

  Sample SAM Template for sam-s3-bucket

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  S3CreationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s3_bucket/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /account
      #       Method: get
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 day)'
            Name: TestSamSchedule
            Description: test schedule of sam lambda
            State: DISABLED


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # S3CreationApi:
  #   Description: API Gateway endpoint URL for Prod stage for Bitcoin Account Balance function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/account/"
  S3CreationFunction:
    Description: AWS S3 bucket creation Lambda Function ARN
    Value: !GetAtt S3CreationFunction.Arn
  S3CreationFunctionIamRole:
    Description: Implicit IAM Role created for Creating S3 bucket function
    Value: !GetAtt S3CreationFunctionRole.Arn
